### ISSUE TITLE
Run task with argument

### ISSUE THREAD

**Issue by alfianyusufabdullah** [JetBrains/educational-plugin#22]
How to run/check task with value from parameter in main function? it's posible?

**Comment by Undin** [comment]
@alfianyusufabdullah Hi!
Do you mean check how `main` function work if some particular command line argument is passed into it? or something else?

**Comment by alfianyusufabdullah** [comment]
Yess @Undin

**Comment by Undin** [comment]
@alfianyusufabdullah 
For example, you can write something like this
```java
import org.junit.Assert;
import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

public class Tests {
    
    @Test
    public void test() {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
        YourClassWithMain.main(new String[]{"YourCommandLineArg"});
        String output = outputStream.toString();
        // check output here
    }
}
```

**Comment by alfianyusufabdullah** [comment]
in kotlin i can't direct access the main function and the command line argument will be set from **_Run/Debug Configuration_**. it's posible to use that? @Undin

**Comment by Undin** [comment]
> in kotlin i can't direct access the main function

I can come up with only one case when it's possible - `main` function is located in private class. But in this case you can make it public. Could you provide a precise example what you want to do?

> the command line argument will be set from Run/Debug Configuration. it's posible to use that?

But they won't be taken into account while task checking because task check doesn't use existing run configuration. So no, you can't use command line arguments from run configuration for task checking

**Comment by alfianyusufabdullah** [comment]
thanks for the time @Undin , i think my case is close.
